### ISSUE TITLE
Add cloud custodian checks for office hours to template

### ISSUE THREAD

**Issue by rochecompaan** [getscaf/sfu-fullstack-template#33]
### 📋 User requirements

Add a minimal example cloud custodian config to the template to enable "office hours" for ec2 instances. For example:
```
policies:
  - name: offhours-ec2
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::1234567890:role/cloud_custodian
    resource: ec2
    filters:
      - type: offhour
        default_tz: America/Indiana/Indianapolis
        offhour: 12
    actions:
      - stop

  - name: onhours-start-ec2
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::1234567890:role/cloud_custodian
    resource: ec2
    filters:
      - type: onhour
        default_tz: America/Indiana/Indianapolis
        onhour: 8
    actions:
      - start
```
